(** This module defines tags that are declared in HTML specification. *)

let span: Dom_html.element Core.tag = "span"
let div: Dom_html.divElement Core.tag = "div"
let input: Dom_html.inputElement Core.tag = "input"
let ul: Dom_html.uListElement Core.tag = "ul"
let li: Dom_html.liElement Core.tag = "li"
let label: Dom_html.labelElement Core.tag = "label"
let section: Dom_html.element Core.tag = "section"
let h1: Dom_html.headingElement Core.tag = "h1"
let h2: Dom_html.headingElement Core.tag = "h2"
let h3: Dom_html.headingElement Core.tag = "h3"
let h4: Dom_html.headingElement Core.tag = "h4"
let h5: Dom_html.headingElement Core.tag = "h5"
let h6: Dom_html.headingElement Core.tag = "h6"
let legend: Dom_html.legendElement Core.tag = "legend"
let a: Dom_html.anchorElement Core.tag = "a"
let button: Dom_html.buttonElement Core.tag = "button"
let form: Dom_html.formElement Core.tag = "form"
let image: Dom_html.imageElement Core.tag = "image"
let pre: Dom_html.preElement Core.tag = "pre"
let textarea: Dom_html.textAreaElement Core.tag = "textarea"
