(** This module defines tags that are declared in HTML specification. *)

let span: Dom_html.element Core.tag = Core.tag_of_string "span"
let div: Dom_html.divElement Core.tag = Core.tag_of_string "div"
let input: Dom_html.inputElement Core.tag = Core.tag_of_string "input"
let ul: Dom_html.uListElement Core.tag = Core.tag_of_string "ul"
let li: Dom_html.liElement Core.tag = Core.tag_of_string "li"
let label: Dom_html.labelElement Core.tag = Core.tag_of_string "label"
let section: Dom_html.element Core.tag = Core.tag_of_string "section"
let h1: Dom_html.headingElement Core.tag = Core.tag_of_string "h1"
let h2: Dom_html.headingElement Core.tag = Core.tag_of_string "h2"
let h3: Dom_html.headingElement Core.tag = Core.tag_of_string "h3"
let h4: Dom_html.headingElement Core.tag = Core.tag_of_string "h4"
let h5: Dom_html.headingElement Core.tag = Core.tag_of_string "h5"
let h6: Dom_html.headingElement Core.tag = Core.tag_of_string "h6"
let legend: Dom_html.legendElement Core.tag = Core.tag_of_string "legend"
let a: Dom_html.anchorElement Core.tag = Core.tag_of_string "a"
let button: Dom_html.buttonElement Core.tag = Core.tag_of_string "button"
let form: Dom_html.formElement Core.tag = Core.tag_of_string "form"
let image: Dom_html.imageElement Core.tag = Core.tag_of_string "image"
let pre: Dom_html.preElement Core.tag = Core.tag_of_string "pre"
let textarea: Dom_html.textAreaElement Core.tag = Core.tag_of_string "textarea"
let header: Dom_html.element Core.tag = Core.tag_of_string "header"
